package usw.pop;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

/**
 * private final LocalDate
 */
public class Customer {
    private String customerID;
    private String fullName;
    private String address;
    private final String email;
    private final List<Booking> packageBookings = new ArrayList<>();
    private final LocalDate signUpDate;
    private BigDecimal packagePoints;
    private final BigDecimal amountSpent;


    public Customer(String fullName, String email, String address) {
        // CustomerID would be autogenerated
        this.fullName = fullName;
        this.email = email;
        this.address = address;
        this.signUpDate = LocalDate.now();
        this.amountSpent = BigDecimal.ZERO;
        this.packagePoints = BigDecimal.ZERO;
    }

    public void addBooking(Booking newBooking) {
        packageBookings.add(newBooking);
        // packagePoints += newBooking
    }

    /**
     * Method that resets the Customer's discount points to 0, for use when applying
     * discounts to holidays
     *
     * @return The amount of discount points
     */
    public BigDecimal usePoints() {
        BigDecimal usePoints = packagePoints;
        packagePoints = BigDecimal.ZERO;
        return usePoints;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getEmail() {
        return email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public List<Booking> getPackageBookings() {
        return packageBookings;
    }
}
