package usw.pop;

import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

/**
 * Represents a flight from one location to another
 */
public class Flight {
    private String flightID;
    private Aircraft aircraft;
    private AircraftCrew aircraftCrew;
    private LocalDateTime flightStart;
    private LocalDateTime flightEnd;
    private final String origAirport;
    private String destAirport;

    /**
     * Creates a {@code Flight} with information
     *
     * @param aircraft Aircraft that the flight is using
     * @param aircraftCrew Crew of the aircraft
     * @param flightStart Date and time when the flight starts
     * @param flightEnd Estimated time when the flight ends
     * @param origAirport Airport the flight is originating from
     * @param destAirport The destination airport
     */
    public Flight(Aircraft aircraft, AircraftCrew aircraftCrew, LocalDateTime flightStart,
                  LocalDateTime flightEnd, String origAirport, String destAirport) {
        // flightID is autogenerated
        this.aircraft = aircraft;
        this.aircraftCrew = aircraftCrew;
        this.flightStart = flightStart;
        this.flightEnd = flightEnd;
        this.origAirport = origAirport;
        this.destAirport = destAirport;
    }

    public String getFlightID() {
        return flightID;
    }

    public void setFlightID(String flightID) {
        this.flightID = flightID;
    }

    public Aircraft getAircraft() {
        return aircraft;
    }

    public void setAircraft(Aircraft aircraft) {
        this.aircraft = aircraft;
    }

    public AircraftCrew getAircraftCrew() {
        return aircraftCrew;
    }

    public void setAircraftCrew(AircraftCrew aircraftCrew) {
        this.aircraftCrew = aircraftCrew;
    }

    public LocalDateTime getFlightStart() {
        return flightStart;
    }

    public void setFlightStart(LocalDateTime flightStart) {
        this.flightStart = flightStart;
    }

    public LocalDateTime getFlightEnd() {
        return flightEnd;
    }

    public void setFlightEnd(LocalDateTime flightEnd) {
        this.flightEnd = flightEnd;
    }

    public long getFlightDuration() {
        return flightStart.until(flightEnd, ChronoUnit.HOURS);
    }

    public String getOrigAirport() {
        return origAirport;
    }

    public String getDestAirport() {
        return destAirport;
    }

    public void setDestAirport(String destAirport) {
        this.destAirport = destAirport;
    }
}
