---
title: Tourism UML
---

classDiagram
  PackageHoliday ..> Flight
  PackageHoliday ..> Cruise
  Plane --|> Aircraft
  Helicopter --|> Aircraft
  Flight ..> Aircraft 
  Flight ..> AircraftCrew 
  Cruise ..> Ship
  Ship ..> ShipCrew
  AircraftCrew *-- Pilot
  AircraftCrew *-- CabinCrew
  ShipCrew *-- ShipCaptain
  ShipCrew *-- ShipEmployee
  Pilot --|> Employee
  CabinCrew --|> Employee
  ShipEmployee --|> Employee
  ShipCaptain --|> Employee

  class PackageHoliday{
    -String packageType
    -Flight flight
    -Cruise cruise
  }
  class Flight{
    -Aircraft aircraft
    -Crew flightCrew
    -int flightDate
  }
  class Aircraft{
    <<interface>>
    -String aircraftRegistration
    -String aircraftManufacturer
    -int fuelAmount
    +fly()
    +land()
    +getAircraftName()
    +refuel(fuelAmount)
  }
  class Helicopter{
    -String helicopterName
    +getAircraftName()
  }
  class Plane{
    -String planeName
    -int callSign
  }
  class Cruise{
    -Ship ship
    +getShip()
  }
  class Ship{
    -String shipName
    -int crewNumber
    +getShipName()
    +getCrewNumber()
  }
  class Employee{
    -int employeeNumber
    -String employeeName
    -int employee
  }
  class AircraftCrew{
    -Array pilotCrew
    -Array cabinCrew 
  }
  class ShipCrew{
    -ShipCaptain shipCaptain
    -Array shipEmployees
  }
  class CabinCrew{
    -String crewPosition
  }
  class Pilot{
    -String pilotLicence 
    -String firstAidLisence
    -String daysFlying
  }
  class ShipEmployee{
    -String crewType
    -String crewBunk
    -String crewArea
  }
  class ShipCaptain{
    -String captainLicence
    -String experience
  }

