---
title: Tourism UML
---

classDiagram
  %% Booking relations
  Customer "1" *-- "*" Booking
  Booking "*" *-- "1" PackageHoliday

  %% Package holiday relations
  PackageHoliday "1" o-- "0..1" Cruise
  PackageHoliday "1" o-- "0..1" Hotel

  %% Flight
  PackageHoliday "*" o-- "0..*" Flight
  Flight "1" o-- "1" AircraftCrew 
  AircraftCrew "1" *-- "0..*" CabinCrew
  AircraftCrew "1" *-- "1..*" Pilot
  Flight o-- Aircraft 
  Plane --|> Aircraft
  Helicopter --|> Aircraft
  Cruise o-- Ship

  Ship *-- ShipCrew
  ShipCrew *-- ShipCaptain
  ShipCrew *-- ShipEmployee
  Cruise o-- PackageRep


  %% Hotel relations
  Hotel o-- PackageRep

  %% Employee relations
  Pilot --|> Employee
  CabinCrew --|> Employee
  ShipEmployee --|> Employee
  ShipCaptain --|> Employee
  PackageRep --|> Employee

  %% Booking classes

  class Customer{
    -String fullName
    -String email
    -String address
    -Date signUpDate
    -int packagePoints
  }
  class Booking{
    -Customer customer
    -PackageHoliday packageHoliday
  }
  class PackageHoliday{
    -String packageType
    -ArrayList~Flight~ flightTo
    -ArrayList~Flight~ flightReturn
    -Cruise cruise
  }

  %% Transport classes

  class Flight{
    -Aircraft aircraft
    -Crew flightCrew
    -int flightDate
  }
  class Cruise{
    -Ship ship
    +getShip()
  }
  class Aircraft{
    <<interface>>
    -String aircraftRegistration
    -String aircraftManufacturer
    -int fuelAmount
    +fly()
    +land()
    +getAircraftName()
    +refuel(fuelAmount)
  }
  class Helicopter{
    -String helicopterName
    +getAircraftName()
  }
  class Plane{
    -String planeName
    -int callSign
  }
  class Ship{
    -String shipName
    -int crewNumber
    +getShipName()
    +getCrewNumber()
  }

  %% Hotel classes

  class Hotel{
    -String location
    -int stars

  }

  %% Employee classes
  class Employee{
    -int employeeNumber
    -String employeeName
    -int employee
  }
  class AircraftCrew{
    -Array pilotCrew
    -Array cabinCrew 
  }
  class ShipCrew{
    -ShipCaptain shipCaptain
    -Array shipEmployees
  }
  class CabinCrew{
    -String crewPosition
  }
  class Pilot{
    -String pilotLicence 
    -String firstAidLisence
    -String daysFlying
  }
  class ShipEmployee{
    -String crewType
    -String crewBunk
    -String crewArea
  }
  class ShipCaptain{
    -String captainLicence
    -String experience
  }
  class PackageRep{
    -String repType
    -String location
  }

